import { useState } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import { useEstoque } from '@/hooks/use-estoque';
import { estoqueApi, EstoqueProduto, ProdutoTipo } from '@/lib/estoque-api';
import { Package, RefreshCw, Upload } from 'lucide-react';

export default function EstoqueAdmin() {
  const { produtos, movimentos, alertas, movimento, bom, consumirComposto, produzir, recarregar } = useEstoque();
  const { toast } = useToast(); const [busca, setBusca] = useState(''); const [arquivo, setArquivo] = useState<File | null>(null); const [selecionado, setSelecionado] = useState<EstoqueProduto | null>(null); const [bomItems, setBomItems] = useState<{ component_id: string; quantity: number }[]>([]);
  const items = (produtos.data || []).filter(p => !busca || `${p.name} ${p.sku} ${p.codes?.map(c => c.code).join(' ') || ''}`.toLowerCase().includes(busca.toLowerCase()));
  const registrar = (p: EstoqueProduto, type: 'IN' | 'ADJUSTMENT' | 'OUT') => { const value = Number(window.prompt('Quantidade')); if (!(value > 0)) return; movimento.mutate({ product_id: p.id, movement_type: type, quantity: value, notes: 'Lançamento administrativo' }, { onSuccess: () => toast({ title: 'Movimento registrado' }), onError: e => toast({ title: 'Erro', description: String(e), variant: 'destructive' }) }); };
  const editarBom = async (p: EstoqueProduto) => { setSelecionado(p); try { setBomItems((await estoqueApi.listarBOM(p.id)).map(i => ({ component_id: i.component_id, quantity: i.quantity }))); } catch { setBomItems([]); } };
  return <MainLayout><div className="space-y-6"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><Package className="h-7 w-7 text-primary" /><div><h1 className="text-2xl font-bold">Estoque</h1><p className="text-sm text-muted-foreground">Itens simples, compostos, BOM e operações.</p></div></div><Button variant="outline" onClick={recarregar}><RefreshCw className="mr-2 h-4 w-4" />Atualizar</Button></div>
  <div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm">Produtos</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{produtos.data?.length ?? '—'}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Alertas</CardTitle></CardHeader><CardContent className="text-2xl font-bold text-destructive">{alertas.data?.length ?? '—'}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Movimentos</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{movimentos.data?.length ?? '—'}</CardContent></Card></div>
  <Tabs defaultValue="produtos"><TabsList><TabsTrigger value="produtos">Produtos</TabsTrigger><TabsTrigger value="movimentos">Movimentos</TabsTrigger><TabsTrigger value="alertas">Alertas</TabsTrigger><TabsTrigger value="importar">Importar XML</TabsTrigger></TabsList><TabsContent value="produtos" className="mt-4"><Card><CardContent className="pt-6"><Input placeholder="Buscar por nome, SKU ou código" value={busca} onChange={e => setBusca(e.target.value)} /><Table className="mt-4"><TableHeader><TableRow><TableHead>SKU</TableHead><TableHead>Produto</TableHead><TableHead>Tipo</TableHead><TableHead>Saldo</TableHead><TableHead>Ações</TableHead></TableRow></TableHeader><TableBody>{items.map(p => <TableRow key={p.id}><TableCell>{p.sku}</TableCell><TableCell>{p.name}</TableCell><TableCell><Badge>{p.product_kind === 'COMPOSITE' ? 'Composto' : 'Simples'}</Badge></TableCell><TableCell>{p.quantity} {p.unit}</TableCell><TableCell className="space-x-1"><Button size="sm" onClick={() => registrar(p, 'IN')}>Entrada</Button><Button size="sm" variant="outline" onClick={() => registrar(p, 'ADJUSTMENT')}>Ajuste</Button>{p.product_kind === 'COMPOSITE' && <><Button size="sm" variant="outline" onClick={() => editarBom(p)}>BOM</Button><Button size="sm" onClick={() => { const q = Number(window.prompt('Quantidade a produzir')); if (q > 0) produzir.mutate({ product_id: p.id, quantity: q }); }}>Produzir</Button><Button size="sm" variant="destructive" onClick={() => { const q = Number(window.prompt('Quantidade a consumir')); if (q > 0) consumirComposto.mutate({ product_id: p.id, quantity: q }); }}>Saída</Button></>}</TableCell></TableRow>)}</TableBody></Table>{selecionado && <Card className="mt-6"><CardHeader><CardTitle>BOM: {selecionado.name}</CardTitle></CardHeader><CardContent className="space-y-2">{bomItems.map((i, n) => <div className="flex gap-2" key={n}><select className="border rounded px-2 flex-1" value={i.component_id} onChange={e => setBomItems(x => x.map((v, j) => j === n ? { ...v, component_id: e.target.value } : v))}><option value="">Selecione o componente</option>{(produtos.data || []).filter(x => x.id !== selecionado.id).map(x => <option key={x.id} value={x.id}>{x.sku} — {x.name}</option>)}</select><Input type="number" min="0.001" value={i.quantity} onChange={e => setBomItems(x => x.map((v, j) => j === n ? { ...v, quantity: Number(e.target.value) } : v))} className="w-28" /><Button variant="ghost" onClick={() => setBomItems(x => x.filter((_, j) => j !== n))}>Remover</Button></div>)}<Button variant="outline" onClick={() => setBomItems(x => [...x, { component_id: '', quantity: 1 }])}>Adicionar componente</Button><Button className="ml-2" onClick={() => bom.mutate({ productId: selecionado.id, items: bomItems.filter(x => x.component_id && x.quantity > 0) })}>Salvar BOM</Button></CardContent></Card>}</CardContent></Card></TabsContent>
  <TabsContent value="movimentos" className="mt-4"><Card><CardContent className="pt-6"><Table><TableHeader><TableRow><TableHead>Data</TableHead><TableHead>Produto</TableHead><TableHead>Tipo</TableHead><TableHead>Quantidade</TableHead><TableHead>Notas</TableHead></TableRow></TableHeader><TableBody>{(movimentos.data || []).map(m => <TableRow key={m.id}><TableCell>{new Date(m.created_at).toLocaleString('pt-BR')}</TableCell><TableCell>{m.name || m.product_id}</TableCell><TableCell><Badge>{m.movement_type}</Badge></TableCell><TableCell>{m.quantity}</TableCell><TableCell>{m.notes || '—'}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card></TabsContent><TabsContent value="alertas"><Card><CardContent className="pt-6">{(alertas.data || []).map(a => <div key={a.id} className="flex justify-between border-b py-3"><span>{a.name || a.product_id}</span><Badge variant="destructive">{a.message}</Badge></div>)}</CardContent></Card></TabsContent><TabsContent value="importar"><Card><CardContent className="pt-6 space-y-4"><Input type="file" accept=".xml,text/xml" onChange={e => setArquivo(e.target.files?.[0] || null)} /><Button disabled={!arquivo} onClick={async () => { if (!arquivo) return; await estoqueApi.importarXml(await arquivo.text()); toast({ title: 'XML importado' }); recarregar(); }}><Upload className="mr-2 h-4 w-4" />Importar XML</Button></CardContent></Card></TabsContent></Tabs></div></MainLayout>;
}
