import { useEffect, useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Checkbox } from '@/components/ui/checkbox';
import { api } from '@/lib/api';
import { useUpload } from '@/hooks/use-upload';
import { useToast } from '@/hooks/use-toast';
import { ArrowDown, ArrowUp, Loader2, Pencil, Plus, Trash2, Upload } from 'lucide-react';

export interface MarketingCategory { id: string; name: string; description?: string | null; is_active: boolean; position: number }
export interface MarketingMaterial { id: string; category_id?: string | null; title: string; description?: string | null; file_url: string; is_active: boolean; is_published: boolean; position: number; category?: MarketingCategory | null }

const base = '/api/comercial/admin/marketing';
export default function AdminComercialMarketingTab() {
  const { toast } = useToast(); const { uploadFile, isUploading, progress } = useUpload();
  const [categories, setCategories] = useState<MarketingCategory[]>([]); const [materials, setMaterials] = useState<MarketingMaterial[]>([]); const [loading, setLoading] = useState(true);
  const [category, setCategory] = useState<Partial<MarketingCategory>>({}); const [material, setMaterial] = useState<Partial<MarketingMaterial>>({}); const [editingCategory, setEditingCategory] = useState<string | null>(null); const [editingMaterial, setEditingMaterial] = useState<string | null>(null);
  const load = async () => { setLoading(true); try { const [c, m] = await Promise.all([api<{ categories: MarketingCategory[] }>(`${base}/categories`), api<{ materials: MarketingMaterial[] }>(`${base}/materials`)]); setCategories(c.categories || []); setMaterials(m.materials || []); } catch (e) { toast({ title: 'Erro ao carregar marketing', description: e instanceof Error ? e.message : 'Tente novamente', variant: 'destructive' }); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const saveCategory = async () => { if (!category.name?.trim()) return; try { const r = editingCategory ? await api<{ category: MarketingCategory }>(`${base}/categories/${editingCategory}`, { method: 'PUT', body: category }) : await api<{ category: MarketingCategory }>(`${base}/categories`, { method: 'POST', body: category }); setCategories(v => editingCategory ? v.map(x => x.id === editingCategory ? r.category : x) : [...v, r.category]); setCategory({}); setEditingCategory(null); toast({ title: 'Categoria salva' }); } catch (e) { toast({ title: 'Erro ao salvar categoria', description: e instanceof Error ? e.message : 'Tente novamente', variant: 'destructive' }); } };
  const removeCategory = async (id: string) => { if (!confirm('Excluir esta categoria?')) return; await api(`${base}/categories/${id}`, { method: 'DELETE' }); load(); };
  const saveMaterial = async () => { if (!material.title?.trim() || !material.file_url) return; try { const r = editingMaterial ? await api<{ material: MarketingMaterial }>(`${base}/materials/${editingMaterial}`, { method: 'PUT', body: material }) : await api<{ material: MarketingMaterial }>(`${base}/materials`, { method: 'POST', body: material }); setMaterials(v => editingMaterial ? v.map(x => x.id === editingMaterial ? r.material : x) : [...v, r.material]); setMaterial({}); setEditingMaterial(null); toast({ title: 'Material salvo' }); } catch (e) { toast({ title: 'Erro ao salvar material', description: e instanceof Error ? e.message : 'Tente novamente', variant: 'destructive' }); } };
  const move = async (kind: 'categories' | 'materials', id: string, direction: 'up' | 'down') => { try { await api(`${base}/${kind}/${id}/order`, { method: 'POST', body: { direction } }); load(); } catch (e) { toast({ title: 'Erro ao ordenar', description: e instanceof Error ? e.message : 'Tente novamente', variant: 'destructive' }); } };
  const toggle = async (kind: 'categories' | 'materials', item: any, field: 'is_active' | 'is_published') => { await api(`${base}/${kind}/${item.id}`, { method: 'PUT', body: { [field]: !item[field] } }); load(); };
  return <div className="grid gap-6 lg:grid-cols-2">
    <Card><CardHeader><CardTitle className="flex items-center justify-between">Categorias <Button size="sm" variant="outline" onClick={() => { setCategory({}); setEditingCategory(null); }}><Plus className="mr-1 h-4 w-4" />Nova</Button></CardTitle></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Input placeholder="Nome da categoria" value={category.name || ''} onChange={e => setCategory({ ...category, name: e.target.value })} /><Textarea placeholder="Descrição (opcional)" value={category.description || ''} onChange={e => setCategory({ ...category, description: e.target.value })} /><Button onClick={saveCategory} disabled={!category.name?.trim()}>{editingCategory ? 'Atualizar' : 'Salvar categoria'}</Button></div>{loading ? <Loader2 className="animate-spin" /> : categories.map((c, i) => <div key={c.id} className="flex items-center justify-between rounded border p-3"><div><b>{c.name}</b>{!c.is_active && <Badge variant="secondary" className="ml-2">Inativa</Badge>}<p className="text-xs text-muted-foreground">{c.description}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" disabled={i === 0} onClick={() => move('categories', c.id, 'up')}><ArrowUp className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={i === categories.length - 1} onClick={() => move('categories', c.id, 'down')}><ArrowDown className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => { setEditingCategory(c.id); setCategory(c); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" onClick={() => toggle('categories', c, 'is_active')}><Checkbox checked={c.is_active} /></Button><Button size="icon" variant="ghost" onClick={() => removeCategory(c.id)}><Trash2 className="h-4 w-4" /></Button></div></div>)}</CardContent></Card>
    <Card><CardHeader><CardTitle>Materiais <Button size="sm" variant="outline" className="float-right" onClick={() => { setMaterial({}); setEditingMaterial(null); }}><Plus className="mr-1 h-4 w-4" />Novo</Button></CardTitle></CardHeader><CardContent className="space-y-3"><Input placeholder="Título" value={material.title || ''} onChange={e => setMaterial({ ...material, title: e.target.value })} /><Textarea placeholder="Descrição" value={material.description || ''} onChange={e => setMaterial({ ...material, description: e.target.value })} /><select className="w-full rounded-md border bg-background p-2 text-sm" value={material.category_id || ''} onChange={e => setMaterial({ ...material, category_id: e.target.value || null })}><option value="">Sem categoria</option>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><Label className="flex cursor-pointer items-center gap-2 rounded border p-2"><Upload className="h-4 w-4" />{isUploading ? `Enviando ${progress}%` : 'Enviar arquivo'}<Input type="file" className="hidden" disabled={isUploading} onChange={async e => { const f = e.target.files?.[0]; if (!f) return; try { const url = await uploadFile(f); setMaterial(v => ({ ...v, file_url: url })); } catch (err) { toast({ title: 'Erro no upload', description: err instanceof Error ? err.message : 'Tente novamente', variant: 'destructive' }); } }} /></Label>{material.file_url && <p className="truncate text-xs text-muted-foreground">{material.file_url}</p>}<Button onClick={saveMaterial} disabled={!material.title?.trim() || !material.file_url || isUploading}>{editingMaterial ? 'Atualizar' : 'Salvar material'}</Button>{materials.map((m, i) => <div key={m.id} className="flex items-center justify-between rounded border p-3"><div><b>{m.title}</b><p className="text-xs text-muted-foreground">{m.category?.name || 'Sem categoria'} · {m.is_published ? 'Publicado' : 'Rascunho'}</p></div><div className="flex gap-1"><Button size="icon" variant="ghost" disabled={i === 0} onClick={() => move('materials', m.id, 'up')}><ArrowUp className="h-4 w-4" /></Button><Button size="icon" variant="ghost" disabled={i === materials.length - 1} onClick={() => move('materials', m.id, 'down')}><ArrowDown className="h-4 w-4" /></Button><Button size="sm" variant="outline" onClick={() => toggle('materials', m, 'is_published')}>{m.is_published ? 'Despublicar' : 'Publicar'}</Button><Button size="icon" variant="ghost" onClick={() => { setEditingMaterial(m.id); setMaterial(m); }}><Pencil className="h-4 w-4" /></Button></div></div>)}</CardContent></Card>
  </div>;
}
